package logic;

import java.time.Year;

/**
 * IncomeReport represents the income report for a specific restaurant. This
 * class extends the Report class.
 */
public class IncomeReport extends Report {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private float TotalRevenue;
	private float SaladRevenue;
	private float SweetsRevenue;
	private float DrinksRevenue;
	private float MainMealRevenue;

	/**
	 * Constructs an IncomeReport with the specified details.
	 *
	 * @param reportID        The unique ID of the report.
	 * @param restaurantID    The ID of the restaurant.
	 * @param year            The year the report is for.
	 * @param month           The month the report is for.
	 * @param reportType      The type of the report.
	 * @param totalRevenue    The total revenue generated by the restaurant.
	 * @param saladRevenue    The revenue generated from salads.
	 * @param sweetsRevenue   The revenue generated from sweets.
	 * @param drinksRevenue   The revenue generated from drinks.
	 * @param mainMealRevenue The revenue generated from main meals.
	 */
	public IncomeReport(int reportID, int restaurantID, Year year, String month, ReportType reportType,
			float totalRevenue, float saladRevenue, float sweetsRevenue, float drinksRevenue, float mainMealRevenue) {
		super(reportID, restaurantID, year, month, reportType);
		TotalRevenue = totalRevenue;
		SaladRevenue = saladRevenue;
		SweetsRevenue = sweetsRevenue;
		DrinksRevenue = drinksRevenue;
		MainMealRevenue = mainMealRevenue;
	}

	/**
	 * Gets the total revenue generated by the restaurant.
	 *
	 * @return The total revenue.
	 */
	public float getTotalRevenue() {
		return TotalRevenue;
	}

	/**
	 * Sets the total revenue generated by the restaurant.
	 *
	 * @param totalRevenue The total revenue to set.
	 */
	public void setTotalRevenue(float totalRevenue) {
		TotalRevenue = totalRevenue;
	}

	/**
	 * Gets the revenue generated from salads.
	 *
	 * @return The salad revenue.
	 */
	public float getSaladRevenue() {
		return SaladRevenue;
	}

	/**
	 * Sets the revenue generated from salads.
	 *
	 * @param saladRevenue The salad revenue to set.
	 */
	public void setSaladRevenue(float saladRevenue) {
		SaladRevenue = saladRevenue;
	}

	/**
	 * Gets the revenue generated from sweets.
	 *
	 * @return The sweets revenue.
	 */
	public float getSweetsRevenue() {
		return SweetsRevenue;
	}

	/**
	 * Sets the revenue generated from sweets.
	 *
	 * @param sweetsRevenue The sweets revenue to set.
	 */
	public void setSweetsRevenue(float sweetsRevenue) {
		SweetsRevenue = sweetsRevenue;
	}

	/**
	 * Gets the revenue generated from drinks.
	 *
	 * @return The drinks revenue.
	 */
	public float getDrinksRevenue() {
		return DrinksRevenue;
	}

	/**
	 * Sets the revenue generated from drinks.
	 *
	 * @param drinksRevenue The drinks revenue to set.
	 */
	public void setDrinksRevenue(float drinksRevenue) {
		DrinksRevenue = drinksRevenue;
	}

	/**
	 * Gets the revenue generated from main meals.
	 *
	 * @return The main meal revenue.
	 */
	public float getMainMealRevenue() {
		return MainMealRevenue;
	}

	/**
	 * Sets the revenue generated from main meals.
	 *
	 * @param mainMealRevenue The main meal revenue to set.
	 */
	public void setMainMealRevenue(float mainMealRevenue) {
		MainMealRevenue = mainMealRevenue;
	}

}
